// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhw-U9AdEPcg_CDh9Q42WdEfHTbKYHfng',
    appId: '1:714043643906:web:f76bc68c0297a95858ef1b',
    messagingSenderId: '714043643906',
    projectId: 'comexamplenontradecement-3835d',
    authDomain: 'comexamplenontradecement-3835d.firebaseapp.com',
    storageBucket: 'comexamplenontradecement-3835d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoJcbU3fR6narbyi-_XJ5B0sfuiLxnH1k',
    appId: '1:714043643906:android:b02e533f0914b3a058ef1b',
    messagingSenderId: '714043643906',
    projectId: 'comexamplenontradecement-3835d',
    storageBucket: 'comexamplenontradecement-3835d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJwpYIYH6wF3wG5IFtZdzsFlYfyw307f0',
    appId: '1:714043643906:ios:be613eef8a26bbe258ef1b',
    messagingSenderId: '714043643906',
    projectId: 'comexamplenontradecement-3835d',
    storageBucket: 'comexamplenontradecement-3835d.appspot.com',
    iosBundleId: 'com.example.nonTradeCementBulkOrderOnly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJwpYIYH6wF3wG5IFtZdzsFlYfyw307f0',
    appId: '1:714043643906:ios:338c0f840d19eec458ef1b',
    messagingSenderId: '714043643906',
    projectId: 'comexamplenontradecement-3835d',
    storageBucket: 'comexamplenontradecement-3835d.appspot.com',
    iosBundleId: 'com.example.nonTradeCementBulkOrderOnly.RunnerTests',
  );
}
